---
title: "Trend of number of measurements"
author: 'Fred Ho'
output:
  html_document:
    df_print: paged
---

# Import data 

Data was curated in Databrick. All participants that had the corresponding risk factors in the GDPPR were included to count number of measurements by year.

```{r, include=F}
library(dbplyr)
library(DBI)
library(tidyverse)
library(lubridate)
library(knitr)

opts_chunk$set(dev=c('png', "tiff"), 
               dev.args=list(tiff=list(compression="lzw")),
               dpi=300)

con <- dbConnect(odbc::odbc(), "Databricks", timeout=5, PWD=Sys.getenv('pwd'))
datp <- tbl(con, in_schema('dars_nic_391419_j3w9t_collab', 
                           'ccu008_pop_all_fh_020323')) %>% 
  collect()

datp <- datp %>% rename(avg=mean, num=n) %>% mutate(num=as.integer(num))
```

```{r, include=F}
tab <- bind_rows(
  datp %>% 
    group_by(mst, year, month) %>% 
    summarise(num=sum(num), .groups='drop') %>% 
    mutate(group='Overall'), 
  datp %>% 
    filter(age_gp %in% c("18-39", "40-59")) %>% 
    group_by(mst, year, month) %>% 
    summarise(num=sum(num), .groups='drop') %>% 
    mutate(group='Age 18-59'), 
  datp %>% 
    filter(age_gp %in% c("60-79", "80+")) %>% 
    group_by(mst, year, month) %>% 
    summarise(num=sum(num), .groups='drop') %>% 
    mutate(group='Age \u2265 60'), 
  datp %>% 
    filter(imd19_q10 < 6) %>% 
    group_by(mst, year, month) %>% 
    summarise(num=sum(num), .groups='drop') %>% 
    mutate(group='IMD < median'), 
  datp %>% 
    filter(imd19_q10 >= 6) %>% 
    group_by(mst, year, month) %>% 
    summarise(num=sum(num), .groups='drop') %>% 
    mutate(group='IMD \u2265 median')
)

tab <- tab %>% 
  mutate(
    date=ymd(paste(year, month, '15')), 
    group=factor(
      group, 
      levels=c('Overall', 'Age 18-59', 'Age \u2265 60', 
               'IMD < median', 'IMD \u2265 median')), 
    num=as.numeric(num)/100000, 
    mst=factor(mst, 
               levels=c('bmi' , 'cig', 'alco', 
                        'sbp' , 'dbp', 'a1c' , 'fg', 
                        'chol', 'ldl', 'hdl' , 'tg', 
                        'ast' , 'alt', 'ggt'         ), 
               labels=c('BMI', 'Cigarette smoking', 'Alcohol consumption', 
                        'SBP', 'DBP', 'HbA1c', 'Fasting glucose', 
                        'Total cholesterol', 'LDL-c', 'HDL-c', 'Triglycerides', 
                        'AST', 'ALT', 'GGT'))) %>% 
  filter(between(date, ymd('2018-10-01'), ymd('2022-12-01'))) %>% 
  arrange(group, mst, date)

tab <- tab %>% 
  left_join(
    tab %>% 
      filter(between(date, ymd('2018-10-01'), ymd('2019-10-01'))) %>% 
      group_by(group, mst) %>% 
      summarise(avg=sum(num)/12),
    by=c('group', 'mst')) %>% 
  group_by(group, mst) %>% 
  mutate(pc=num/avg*100) %>% 
  ungroup()
```

# Total number of measurements 

```{r, fig.dim=c(8, 8), echo=F, warning=F}
ggplot(tab %>% filter(group=='Overall'), aes(x=date, y=num)) + 
  geom_line() + 
  ylab('Number of measurements (\'00,000)') + xlab('') + 
  facet_wrap(vars(mst), scales='free')
```

# Number of measurements by age

```{r, fig.dim=c(10, 8), echo=F, warning=F}
ggplot(tab %>% filter(group %in% c('Age 18-59', 'Age \u2265 60')), 
       aes(x=date, y=num, col=group)) + 
  geom_line() + 
  ylab('Number of measurements (\'00,000)') + xlab('') + 
  theme(legend.title = element_blank()) + 
  facet_wrap(vars(mst), scales='free')
```

# Number of measurements by IMD

```{r, fig.dim=c(10, 8), echo=F, warning=F}
ggplot(tab %>% filter(group %in% c('IMD \u2265 median', 'IMD < median')), 
       aes(x=date, y=num, col=group)) + 
  geom_line() + 
  ylab('Number of measurements (\'00,000)') + xlab('') + 
  theme(legend.title = element_blank()) + 
  facet_wrap(vars(mst), scales='free')
```

# Percentage changes of measurements

```{r, fig.dim=c(10, 8), echo=F, warning=F}
ggplot(tab, aes(x=date, y=pc, col=group)) + 
  geom_hline(yintercept=100, linetype='dashed', colour='darkgrey') + 
  geom_line(alpha=.5) + 
  ylab('Number of measurements (% compared to 2018-19)') + xlab('') + 
  theme(legend.title = element_blank()) + 
  facet_wrap(vars(mst), scales='fixed')
```